logging:
  level:
    root: debug
spring:
  application:
    name: quickstart
  main:

    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://127.0.0.1/demo_security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  servlet:
    context-path: /quickstart
  port: 18900